name: remonitor
description: Remonitor is remote monitor

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  provider: ^4.0.0
  sqflite: ^1.2.0
  path: ^1.6.4
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7

flutter:
  uses-material-design: true